#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   xcv58 <i@xcv58.com>
#

insertPath () {
    [[ -d ${*} ]] && export PATH=${*}:${PATH}
}

appendPath () {
    [[ -d ${*} ]] && export PATH=${PATH}:${*}
}

sourceFile () {
    [[ -s ${*} ]] && source ${*}
}

exportENV () {
    [[ -d $2 ]] && {
        export ${1}=${2}
    }
}

# clear Docker container by name
clearContainer() {
    docker ps -q --filter "name=${1}" | xargs -n 1 docker stop
    docker ps -a -q --filter "name=${1}" | xargs -n 1 docker rm
}

# TODO: need check whether is has 256color support
if [[ "$TERM" == "xterm" ]]; then
    export TERM=xterm-256color
fi

# Source Prezto.
sourceFile "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# Customize to your needs...

# for autojump
function load_autojump() {
    (( $+commands[brew] )) && {
        [[ `uname` == "Linux" && -f /usr/share/autojump/autojump.zsh ]] && source /usr/share/autojump/autojump.zsh
        [[ `uname` == "Darwin" && -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && source $(brew --prefix)/etc/profile.d/autojump.sh
    }
}
lazy_load load_autojump j

# for Emacs and EmacsClient
alias ec="emacsclient -n"

export ALTERNATE_EDITOR="vim"

# Path for groovy
exportENV GROOVY_HOME /usr/local/opt/groovy/libexec

# Path for /usr/local/bin
insertPath /usr/local/bin

# Path for go lib
insertPath /usr/local/opt/go/libexec/bin/bin

# add current directory to PATH
export PATH=.:${PATH}

# Path for bins
export PATH=${PATH}:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin

# Path for Android
[[ -d ~/SDK-Android ]] && {
    export ANDROID_HOME=~/SDK-Android
    appendPath ${ANDROID_HOME}
    appendPath ${ANDROID_HOME}/platform-tools
}

exportENV ANDROID_NDK_HOME ~/Library/Android/android-ndk

# Set Gradle_HOME
exportENV GRADLE_HOME /usr/local/Cellar/gradle/2.6

# HADOOP related variables and Path
[[ -d ~/hadoop ]] && {
    export HADOOP_INSTALL=~/hadoop
    export HADOOP_HOME=$HADOOP_INSTALL
    export PATH=${PATH}:$HADOOP_INSTALL/bin:$HADOOP_INSTALL/sbin
    export HADOOP_MAPRED_HOME=$HADOOP_INSTALL
    export HADOOP_COMMON_HOME=$HADOOP_INSTALL
    export HADOOP_HDFS_HOME=$HADOOP_INSTALL
    export YARN_HOME=$HADOOP_INSTALL
}

# For sed error: illegal byte sequence. via http://stackoverflow.com/questions/19242275/re-error-illegal-byte-sequence-on-mac-os-x
export LC_CTYPE=C
export LANG=C

# Fix jekyll "invalid byte sequence in US-ASCII" error
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# for emacs term
if [[ -n ${INSIDE_EMACS} ]]; then
        # This shell runs inside an Emacs *shell*/*term* buffer.
        prompt walters
        unsetopt zle
fi

# Path for RVM
appendPath $HOME/.rvm/bin

# node path
exportENV NODE_PATH /usr/local/lib/node_modules

# for OS161 CSE 521
[[ -d ~/root && -d ~/os161 && -d ~/src ]] && {
    alias db="cd ~/root && mips-harvard-os161-gdb kernel"
    appendPath ~/os161/tools/bin
}

# Vi Mode
sourceFile "${ZDOTDIR:-$HOME}/.zshrc_vimode.zsh"

# for alias
sourceFile "${ZDOTDIR:-$HOME}/.zshrc_alias.zsh"

# for AppleScript Alias
sourceFile "${ZDOTDIR:-$HOME}/.zshrc_scpt_alias.zsh"

# # local config
sourceFile "${ZDOTDIR:-$HOME}/.zshrc_local"

# The next line updates PATH for the Google Cloud SDK.
sourceFile "${ZDOTDIR:-$HOME}/google-cloud-sdk/path.zsh.inc"

# The next line enables shell command completion for gcloud.
sourceFile "${ZDOTDIR:-$HOME}/google-cloud-sdk/completion.zsh.inc"

# Go Version Manager
sourceFile "${ZDOTDIR:-$HOME}/.gvm/scripts/gvm"

# for Mac OS only
[[ `uname` == "Darwin" ]] && sourceFile "${ZDOTDIR:-$HOME}/.zshrc_mac.zsh"
